### ISSUE TITLE
Missing documentation for SMS 2FA

### ISSUE THREAD

**Issue by vojtechkubin** [zonkyio/zonky-api#34]
Hello,

when I request "/users/me/wallet/transactions" the response is `{error:"'AUTHORIZATION_SMS_REQUIRED'"}`, but I cannot figure out where should I send the SMS code. The documentation does not specify that.

I would appreciate if you could add it.

**Comment by lukasnovy** [comment]
Due to legal regulations we are allowed to display money operations only to subjects holding PSD2 licence. These subjects should use openbanking api instead of our regular api. I'm sorry but we are not able to help you with this request. 

Endpoints approved for public api doesn't need 2FA authorization.
